import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/redux/ReduxProvider";
import NextTopLoader from "nextjs-toploader";
import { ThemeProvider } from "@/context/ThemeProvider";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { Toaster } from "sonner";
import NextAuthProvider from "@/context/NextAuthProvider";
import Master from "@/components/layouts/dashboard/Master";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOption } from "../api/auth/[...nextauth]/route";
import QueryClientProvider from "@/context/QueryClientProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOption);

  if (session === null) {
    return redirect("/auth/signin");
  }
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-background`}
        suppressHydrationWarning={true}
      >
        <ReduxProvider>
          <NextTopLoader
            color="#05b6d3"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={true}
            easing="ease"
            speed={200}
            shadow="0 0 10px #05b6d3,0 0 5px #45c6c0"
          />
          <EdgeStoreProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NextAuthProvider>
                <QueryClientProvider>
                  <Master>{children}</Master>
                </QueryClientProvider>
                <Toaster position="top-right" />
              </NextAuthProvider>
            </ThemeProvider>
          </EdgeStoreProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
